title: 徐彦彦 | 武汉大学测绘遥感信息工程全国重点实验室
baseURL: https://XuYanyanwhu.github.io
defaultContentLanguage: zh
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
